terasolunaorg/terasoluna-tourreservation

- terasoluna-tourreservation-domain/pom.xml
- terasoluna-tourreservation-domain/src/main/java/org/terasoluna/tourreservation/domain/service/reserve/ReserveServiceImpl.java
- terasoluna-tourreservation-domain/src/main/java/org/terasoluna/tourreservation/domain/service/tourinfo/TourInfoSharedServiceImpl.java
- terasoluna-tourreservation-domain/src/main/resources/META-INF/spring/tourreservation-domain.xml
- terasoluna-tourreservation-domain/src/test/java/org/terasoluna/tourreservation/domain/service/reserve/ReserveServiceImplTest.java
- terasoluna-tourreservation-domain/src/test/java/org/terasoluna/tourreservation/domain/service/tourinfo/TourInfoServiceImplTest.java
- terasoluna-tourreservation-domain/src/test/java/org/terasoluna/tourreservation/domain/service/tourinfo/TourInfoSharedServiceImplTest.java
- terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/TourSearchValidateTest.java
- terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/managereservation/ReportingHelper.java
- terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/searchtour/DepYearCodeList.java
- terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/searchtour/SearchTourController.java
- terasoluna-tourreservation-web/src/test/java/org/terasoluna/tourreservation/app/searchtour/SearchTourControllerTest.java
> Modified to use JodaTimeDateFactory. #168

- .travis.yml
> add -U option #170

- terasoluna-tourreservation-domain/pom.xml
- terasoluna-tourreservation-env/pom.xml
- terasoluna-tourreservation-initdb/pom.xml
- terasoluna-tourreservation-parent/pom.xml
- terasoluna-tourreservation-selenium/pom.xml
- terasoluna-tourreservation-web/pom.xml
please review terasolunaorg/terasoluna-tourreservation#166
> reversion 1.1.0 -> 5.0.0 terasolunaorg/terasoluna-tourreservation#166

- terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/TourSearchValidateTest.java
Please review terasolunaorg/terasoluna-tourreservation#177, and merge to master branch.
> Setted size of window terasolunaorg/terasoluna-tourreservation#177

- terasoluna-tourreservation-domain/src/test/java/org/terasoluna/tourreservation/domain/repository/tourinfo/TourInfoRepositoryImplTest.java
Please reivew terasolunaorg/terasoluna-tourreservation#179, and merge to master branch.
> Changed to past date terasolunaorg/terasoluna-tourreservation#179

- terasoluna-tourreservation-web/src/main/resources/ValidationMessages.properties
Please review terasolunaorg/terasoluna-tourreservation#176, and merget to master branch.
> Added ValidationMessages.properties

- terasoluna-tourreservation-parent/pom.xml
Please review terasolunaorg/terasoluna-tourreservation#185, and merge to master branch.
> Deleted h2 dependency in the parent 

- terasoluna-tourreservation-domain/pom.xml
- terasoluna-tourreservation-env/pom.xml
- terasoluna-tourreservation-initdb/pom.xml
- terasoluna-tourreservation-parent/pom.xml
- terasoluna-tourreservation-selenium/pom.xml
- terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/LogInReservUpdateTest.java
- terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/TokenCheckErrorTest.java
- terasoluna-tourreservation-web/pom.xml
Please review terasolunaorg/terasoluna-tourreservation#188, and merge to master branch.
> Changed framework name terasolunaorg/terasoluna-tourreservation#188

- terasoluna-tourreservation-domain/pom.xml
- terasoluna-tourreservation-parent/pom.xml
- terasoluna-tourreservation-selenium/pom.xml
- terasoluna-tourreservation-web/pom.xml
Please review terasolunaorg/terasoluna-tourreservation#191, and merge to master branch.
> Set scope(test,provided) terasolunaorg/terasoluna-tourreservation#191

- terasoluna-tourreservation-domain/src/main/java/org/terasoluna/tourreservation/domain/service/tourinfo/PriceCalculateSharedServiceImpl.java
`@Transactional` does not work on `@PostConstruct`'s method. 
e,g)
```java
@Transactional
@PostConstruct
public void loadAges() {
// ...
}     
```
Therefore, i manage a transaction manually using the `TransactionTemplate`.
Please review #163 .
> Manage a transaction to disable the read only flag in loadAges. #163

- README.md
> Polishing README.md on 1.0.x. terasolunaorg/terasoluna-tourreservation#201

- README.md
> Update README.md for 5.x. terasolunaorg/terasoluna-tourreservation#199

- README.md
(cherry picked from commit c4685b1a9045c2ddd6de83d2667c8786b9b06809)
Please review #199 .
> [5.0.x] Update README.md for 5.x. terasolunaorg/terasoluna-tourreservation#199

- terasoluna-tourreservation-domain/pom.xml
- terasoluna-tourreservation-env/pom.xml
- terasoluna-tourreservation-initdb/pom.xml
- terasoluna-tourreservation-parent/pom.xml
- terasoluna-tourreservation-selenium/pom.xml
- terasoluna-tourreservation-web/pom.xml
> Upgrade Version to 5.1.0-SNAPSHOT. #203

- terasoluna-tourreservation-domain/pom.xml
- terasoluna-tourreservation-env/pom.xml
- terasoluna-tourreservation-initdb/pom.xml
- terasoluna-tourreservation-parent/pom.xml
- terasoluna-tourreservation-selenium/pom.xml
- terasoluna-tourreservation-web/pom.xml
> Upgrade Version to 5.0.1-SNAPSHOT. #204

- terasoluna-tourreservation-domain/pom.xml
- terasoluna-tourreservation-env/pom.xml
- terasoluna-tourreservation-initdb/pom.xml
- terasoluna-tourreservation-parent/pom.xml
- terasoluna-tourreservation-selenium/pom.xml
- terasoluna-tourreservation-web/pom.xml
> Upgrade Version to 1.0.3-SNAPSHOT. #205

- .gitignore
> Ignore IDEA project file. terasolunaorg/terasoluna-tourreservation#220

- terasoluna-tourreservation-domain/src/main/java/org/terasoluna/tourreservation/domain/service/userdetails/ReservationUserDetailsService.java
Please review terasolunaorg/terasoluna-tourreservation#174 .
> Remove todo for UsernameNotFoundException's message. terasolunaorg/terasoluna-tourreservation#174

- .travis.yml
Please review terasolunaorg/terasoluna-tourreservation#222 .
> Support JDK8 on travis. terasolunaorg/terasoluna-tourreservation#222

- terasoluna-tourreservation-web/src/main/webapp/WEB-INF/views/common/error/not-found-error.jsp
- terasoluna-tourreservation-web/src/main/webapp/WEB-INF/web.xml
Please review terasolunaorg/terasoluna-tourreservation#94 .
> Add not found page. terasolunaorg/terasoluna-tourreservation#94

- terasoluna-tourreservation-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml
- terasoluna-tourreservation-env/configs/tomcat8-postgresql/resources/META-INF/spring/tourreservation-codelist.properties
- terasoluna-tourreservation-env/configs/tomcat8-postgresql/resources/META-INF/spring/tourreservation-env.xml
- terasoluna-tourreservation-env/configs/tomcat8-postgresql/resources/META-INF/spring/tourreservation-infra.properties
- terasoluna-tourreservation-env/configs/tomcat8-postgresql/resources/logback.xml
- terasoluna-tourreservation-env/pom.xml
Please review terasolunaorg/terasoluna-tourreservation#214 .
> Support tomcat8 terasolunaorg/terasoluna-tourreservation#214

- .travis.yml
(cherry picked from commit 72990e8308ef570f8cdc6d8054f29c96bac7b230)
Please review terasolunaorg/terasoluna-tourreservation#222.
> [5.0.x] Support JDK8 on travis. terasolunaorg/terasoluna-tourreservation#222

- terasoluna-tourreservation-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml
- terasoluna-tourreservation-env/configs/tomcat8-postgresql/resources/META-INF/spring/tourreservation-codelist.properties
- terasoluna-tourreservation-env/configs/tomcat8-postgresql/resources/META-INF/spring/tourreservation-env.xml
- terasoluna-tourreservation-env/configs/tomcat8-postgresql/resources/META-INF/spring/tourreservation-infra.properties
- terasoluna-tourreservation-env/configs/tomcat8-postgresql/resources/logback.xml
- terasoluna-tourreservation-env/pom.xml
(cherry picked from commit 82ca3cd6bc802a779d6ccd2aecc03fa4b623dc83)
Please review terasolunaorg/terasoluna-tourreservation#214 .
> [5.0.x] Support tomcat8 terasolunaorg/terasoluna-tourreservation#214

- .gitignore
(cherry picked from commit 7a241e74bb30ef0692a6de4191d1c8844a97e2c7)
Please review terasolunaorg/terasoluna-tourreservation#220 .
> [1.0.x] Ignore IDEA project file. terasolunaorg/terasoluna-tourreservation#220

- terasoluna-tourreservation-domain/pom.xml
- terasoluna-tourreservation-env/pom.xml
- terasoluna-tourreservation-parent/pom.xml
- terasoluna-tourreservation-selenium/pom.xml
- terasoluna-tourreservation-web/pom.xml
Please review terasolunaorg/terasoluna-tourreservation#212 .
> Polish pom.xml. terasolunaorg/terasoluna-tourreservation#212

- .travis.yml
- terasoluna-tourreservation-initdb/pom.xml
> #162: Fix travis errors

- terasoluna-tourreservation-domain/pom.xml
- terasoluna-tourreservation-env/pom.xml
- terasoluna-tourreservation-parent/pom.xml
- terasoluna-tourreservation-selenium/pom.xml
- terasoluna-tourreservation-web/pom.xml
(cherry picked from commit b638ffc7e5a1648e61f844e2bf3a0f66a2edef8c)
Please review terasolunaorg/terasoluna-tourreservation#212 .
> [5.0.x] Polish pom.xml. terasolunaorg/terasoluna-tourreservation#212

- .travis.yml
- terasoluna-tourreservation-initdb/pom.xml
(cherry picked from commit 2481e9d8bd7b1c4e5bf28247c6c3b956696d7789)
Please review terasolunaorg/terasoluna-tourreservation#162 .
> [5.0.x] Fix travis errors terasolunaorg/terasoluna-tourreservation#162

- .travis.yml
- terasoluna-tourreservation-initdb/pom.xml
(cherry picked from commit 2481e9d8bd7b1c4e5bf28247c6c3b956696d7789)
Please review terasolunaorg/terasoluna-tourreservation#162 .
> [1.0.x] Fix travis errors terasolunaorg/terasoluna-tourreservation#162

- terasoluna-tourreservation-domain/pom.xml
- terasoluna-tourreservation-env/pom.xml
- terasoluna-tourreservation-initdb/pom.xml
- terasoluna-tourreservation-parent/pom.xml
- terasoluna-tourreservation-selenium/pom.xml
- terasoluna-tourreservation-web/pom.xml
> #239: Update to 1.0.4-SNAPSHOT

- terasoluna-tourreservation-domain/pom.xml
- terasoluna-tourreservation-env/pom.xml
- terasoluna-tourreservation-initdb/pom.xml
- terasoluna-tourreservation-parent/pom.xml
- terasoluna-tourreservation-selenium/pom.xml
- terasoluna-tourreservation-web/pom.xml
> #240: Update to 5.0.2-SNAPSHOT

- terasoluna-tourreservation-domain/src/main/java/org/terasoluna/tourreservation/domain/service/reserve/AuthorizedReserveSharedService.java
- terasoluna-tourreservation-domain/src/main/java/org/terasoluna/tourreservation/domain/service/reserve/AuthorizedReserveSharedServiceImpl.java
- terasoluna-tourreservation-domain/src/main/java/org/terasoluna/tourreservation/domain/service/reserve/ReserveServiceImpl.java
- terasoluna-tourreservation-domain/src/test/java/org/terasoluna/tourreservation/domain/service/reserve/ReserveServiceImplTest.java
- terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/UnauthorizedAccessTest.java
- terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-mvc.xml
- terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-security.xml
Please review terasolunaorg/terasoluna-tourreservation#213 .
> Implement access control for other owner resource. terasolunaorg/terasoluna-tourreservation#213

- terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/managereservation/ManageReservationController.java
- terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/reservetour/ReserveTourController.java
- terasoluna-tourreservation-web/src/test/java/org/terasoluna/tourreservation/app/managereservation/ManageReservationControllerTest.java
- terasoluna-tourreservation-web/src/test/java/org/terasoluna/tourreservation/app/reservetour/ReserveTourControllerTest.java
Please review terasolunaorg/terasoluna-tourreservation#256 .
> Remove exporting logic of path variable value at the time of redirect. terasolunaorg/terasoluna-tourreservation#256

- terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/managereservation/ManageReservationController.java
- terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/reservetour/ReserveTourController.java
- terasoluna-tourreservation-web/src/test/java/org/terasoluna/tourreservation/app/managereservation/ManageReservationControllerTest.java
- terasoluna-tourreservation-web/src/test/java/org/terasoluna/tourreservation/app/reservetour/ReserveTourControllerTest.java
(cherry picked from commit 008a21240e0ccce657a54650dba2e0e77fde9ce5)
Please review terasolunaorg/terasoluna-tourreservation#256 .
> [5.0.x] Remove exporting logic of path variable value at the time of redirect. terasolunaorg/terasoluna-tourreservation#256

- terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/searchtour/SearchTourController.java
- terasoluna-tourreservation-web/src/main/webapp/WEB-INF/views/menu/menu.jsp
Please review terasolunaorg/terasoluna-tourreservation#258 .
> Modify execution timing of SessionStatus#complete. terasolunaorg/terasoluna-tourreservation#258

- terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/searchtour/SearchTourController.java
- terasoluna-tourreservation-web/src/main/webapp/WEB-INF/views/menu/menu.jsp
(cherry picked from commit c387adbc6805f6c31eb6bde6e2c2eca9e8997cd8)
Please review terasolunaorg/terasoluna-tourreservation#258 .
> [5.0.x] Modify execution timing of SessionStatus#complete. terasolunaorg/terasoluna-tourreservation#258

- .travis.yml
- terasoluna-tourreservation-parent/pom.xml
> #76: Support selenium on travis-CI

- .travis.yml
- terasoluna-tourreservation-parent/pom.xml
(cherry picked from commit cbf4f6349ee164f821cc22d5cc6a7b9667bb2d98)
Please review #76 .
> [5.0.x] #76: Support selenium on travis-CI

- .travis.yml
- terasoluna-tourreservation-parent/pom.xml
(cherry picked from commit cbf4f6349ee164f821cc22d5cc6a7b9667bb2d98)
Conflicts:
terasoluna-tourreservation-parent/pom.xml
Conflicts resolved by manually.
Please review #76 .
> [1.0.x] #76: Support selenium on travis-CI

- README.md
Please review terasolunaorg/terasoluna-tourreservation#76.
> Update 'Deploy war' in README.md terasolunaorg/terasoluna-tourreservation#76

- terasoluna-tourreservation-domain/src/test/java/org/terasoluna/tourreservation/domain/service/reserve/ReserveServiceImplSecurityTest.java
- terasoluna-tourreservation-domain/src/test/resources/org/terasoluna/tourreservation/domain/service/reserve/ReserveServiceImplSecurityTest-context.xml
I've added test cases for `@PostAuthorize`.
Please review terasolunaorg/terasoluna-tourreservation#213 .
> Add unit tests for method security. terasolunaorg/terasoluna-tourreservation#213

- terasoluna-tourreservation-domain/src/main/java/org/terasoluna/tourreservation/domain/service/reserve/AuthorizedReserveSharedService.java
- terasoluna-tourreservation-domain/src/main/java/org/terasoluna/tourreservation/domain/service/reserve/AuthorizedReserveSharedServiceImpl.java
- terasoluna-tourreservation-domain/src/main/java/org/terasoluna/tourreservation/domain/service/reserve/ReserveServiceImpl.java
- terasoluna-tourreservation-domain/src/test/java/org/terasoluna/tourreservation/domain/service/reserve/ReserveServiceImplSecurityTest.java
- terasoluna-tourreservation-domain/src/test/java/org/terasoluna/tourreservation/domain/service/reserve/ReserveServiceImplTest.java
- terasoluna-tourreservation-domain/src/test/resources/org/terasoluna/tourreservation/domain/service/reserve/ReserveServiceImplSecurityTest-context.xml
- terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/UnauthorizedAccessTest.java
- terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-mvc.xml
- terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-security.xml
Please review terasolunaorg/terasoluna-tourreservation#213.
> [5.0.x] Implement access control for other owner resource. terasolunaorg/terasoluna-tourreservation#213

- .travis.yml
Please review terasolunaorg/terasoluna-tourreservation#273.
> travis-ci migrate to container-based infrastructure. terasolunaorg/terasoluna-tourreservation#273

- .travis.yml
Please review terasolunaorg/terasoluna-tourreservation#273.
I've changed default branch(`master` -> `5.0.x`).
> [5.0.x] Install latest snapshot of terasoluna-gfw before running build. terasolunaorg/terasoluna-tourreservation#273

- .travis.yml
Please review terasolunaorg/terasoluna-tourreservation#273.
I've changed default branch (`master` - > `1.0.x`).
> [1.0.x] Install latest snapshot of terasoluna-gfw before running build. terasolunaorg/terasoluna-tourreservation#273

- terasoluna-tourreservation-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml
- terasoluna-tourreservation-env/configs/tomcat-postgresql/resources/META-INF/spring/tourreservation-env.xml
- terasoluna-tourreservation-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml
- terasoluna-tourreservation-env/configs/tomcat8-postgresql/resources/META-INF/spring/tourreservation-env.xml
- terasoluna-tourreservation-env/src/main/resources/META-INF/spring/tourreservation-env.xml
> changed data source name #102

- terasoluna-tourreservation-web/src/main/webapp/WEB-INF/web.xml
Please review terasolunaorg/terasoluna-tourreservation#282.
> Add session-config(tracking mode & session timeout) in web.xml terasolunaorg/terasoluna-tourreservation#282

- terasoluna-tourreservation-domain/pom.xml
- terasoluna-tourreservation-domain/src/test/java/org/terasoluna/tourreservation/domain/service/reserve/ReserveServiceImplSecurityTest.java
Please review terasolunaorg/terasoluna-tourreservation#287.
> Modify to use spring-security-test APIs on ReserveServiceImplSecurityTest terasolunaorg/terasoluna-tourreservation#287

- terasoluna-tourreservation-web/src/main/webapp/WEB-INF/web.xml
(cherry picked from commit 019220a8eb20d881acb679830f0fcf87b7f2ee93)
Please review terasolunaorg/terasoluna-tourreservation#282.
> [5.0.x] Add session-config(tracking mode & session timeout) in web.xml terasolunaorg/terasoluna-tourreservation#282

- .travis.yml
- pom.xml
Please review terasolunaorg/terasoluna-tourreservation#295.
> Update PostgreSQL 9.4 on Travis-CI terasolunaorg/terasoluna-tourreservation#295

- terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/common/FunctionTestSupport.java
- terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/CustomerRegisterTest.java
- terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/CustomerRegisterValidateTest.java
- terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/LanguageSwitchTest.java
- terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/LogInLogOutTest.java
- terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/LogInReservUpdateTest.java
- terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/SystemErrorTest.java
- terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/TokenCheckErrorTest.java
- terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/TourSearchPaginationTest.java
- terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/TourSearchRegistValidateTest.java
- terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/TourSearchValidateTest.java
- terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/UnLogInTourSearchTest.java
- terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/UnauthorizedAccessTest.java
- terasoluna-tourreservation-selenium/src/test/resources/META-INF/spring/selenium.properties
- terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-mvc.xml
- terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-security.xml
- terasoluna-tourreservation-web/src/main/webapp/WEB-INF/views/menu/menu.jsp
- terasoluna-tourreservation-web/src/main/webapp/WEB-INF/web.xml
Please review terasolunaorg/terasoluna-tourreservation#297.
> Add functionality to switch a language using UI terasolunaorg/terasoluna-tourreservation#297

- terasoluna-tourreservation-initdb/pom.xml
> Remove onError option for sql-maven-plugin #303

- .travis.yml
- terasoluna-tourreservation-parent/pom.xml
I've backported to 5.0.x, please review terasolunaorg/terasoluna-tourreservation#295.
> [5.0.x] Update PostgreSQL 9.4 on Travis-CI terasolunaorg/terasoluna-tourreservation#295

- .travis.yml
- terasoluna-tourreservation-domain/pom.xml
- terasoluna-tourreservation-initdb/pom.xml
- terasoluna-tourreservation-parent/pom.xml
- terasoluna-tourreservation-selenium/pom.xml
I've backported to 1.0.x, please review terasolunaorg/terasoluna-tourreservation#295.
> [1.0.x] Update PostgreSQL 9.4 on Travis-CI terasolunaorg/terasoluna-tourreservation#295

- pom.xml
Please review terasolunaorg/terasoluna-tourreservation#307.
> Update Tomcat 8.0.29 on Travis-CI terasolunaorg/terasoluna-tourreservation#307

- terasoluna-tourreservation-parent/pom.xml
I've backported to 5.0.x, please review terasolunaorg/terasoluna-tourreservation#307.
> [5.0.x] Update Tomcat 8.0.29 on Travis-CI terasolunaorg/terasoluna-tourreservation#307

- terasoluna-tourreservation-parent/pom.xml
I've backported to 1.0.x, please review terasolunaorg/terasoluna-tourreservation#307.
> [1.0.x] Update Tomcat 8.0.29 on Travis-CI terasolunaorg/terasoluna-tourreservation#307

- terasoluna-tourreservation-initdb/pom.xml
(cherry picked from commit dd9d20c4267efe0205f33951deb90955f90b5e70)
Please review #303 .
> [5.0.x] Remove onError option for sql-maven-plugin #303

- terasoluna-tourreservation-initdb/pom.xml
(cherry picked from commit dd9d20c4267efe0205f33951deb90955f90b5e70)
Please review #303 .
> [1.0.x] Remove onError option for sql-maven-plugin #303

- pom.xml
Please review terasolunaorg/terasoluna-tourreservation#319.
> Update Tomcat 8.0.30 on Travis-CI terasolunaorg/terasoluna-tourreservation#319

- terasoluna-tourreservation-parent/pom.xml
Please review terasolunaorg/terasoluna-tourreservation#319.
> [5.0.x] Update Tomcat 8.0.30 on Travis-CI terasolunaorg/terasoluna-tourreservation#319

- terasoluna-tourreservation-parent/pom.xml
Please review terasolunaorg/terasoluna-tourreservation#319.
> [1.0.x] Update Tomcat 8.0.30 on Travis-CI terasolunaorg/terasoluna-tourreservation#319

- terasoluna-tourreservation-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml.env.ftl
- terasoluna-tourreservation-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml.env.ftl
> replace config

- terasoluna-tourreservation-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml
- terasoluna-tourreservation-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml
#327
created environment config by replace config tool
> created environment config by replace config tool

- terasoluna-tourreservation-env/configs/resin-postgresql/ContainerConfigXML/app-terasoluna-tourreservation-web.xml.env.ftl
- terasoluna-tourreservation-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml.env.ftl
#325 
#327
git cherry-pick 0b98c596eb261b066c620908e04e8db4f03b0d6d
git cherry-pick 5795c1b2d35c5702b4f1f300fdccf8b3ac93ff35
> cherry pick replace tool 1.0.x

- .travis.yml
- pom.xml
> Modify to use parent configurations for cargo-maven2-plugin #334

- .travis.yml
- terasoluna-tourreservation-parent/pom.xml
I've backported to 1.0.x by manually.
Please review #334 .
> [1.0.x] Modify to use parent configurations for cargo-maven2-plugin #334

- .travis.yml
- terasoluna-tourreservation-parent/pom.xml
I've backported to 5.0.x by manually.
Please review #334 .
> [5.0.x] Modify to use parent configurations for cargo-maven2-plugin #334

- terasoluna-tourreservation-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml
- terasoluna-tourreservation-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml.env.ftl
- terasoluna-tourreservation-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml
- terasoluna-tourreservation-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml.env.ftl
#325 
#327
git cherry-pick 0b98c596eb261b066c620908e04e8db4f03b0d6d
git cherry-pick 5795c1b2d35c5702b4f1f300fdccf8b3ac93ff35
> cherry pick replace tool 5.0.x

- terasoluna-tourreservation-domain/src/test/java/org/terasoluna/tourreservation/domain/repository/reserve/ReserveRepositoryImplTest.java
Please review terasolunaorg/terasoluna-tourreservation#345 .
> Fix error of ReserveRepositoryImplTest#testFindByCustomer01 terasolunaorg/terasoluna-tourreservation#345

- terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/managereservation/ManageReservationController.java
- terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/reservetour/ReserveTourController.java
- terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-mvc.xml
- terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-security.xml
- terasoluna-tourreservation-web/src/main/webapp/WEB-INF/views/common/top.jsp
- terasoluna-tourreservation-web/src/main/webapp/WEB-INF/views/login/form.jsp
- terasoluna-tourreservation-web/src/main/webapp/WEB-INF/views/menu/menu.jsp
- terasoluna-tourreservation-web/src/main/webapp/WEB-INF/views/reservetour/reserveForm.jsp
- terasoluna-tourreservation-web/src/main/webapp/WEB-INF/views/searchtour/searchForm.jsp
- terasoluna-tourreservation-web/src/test/java/org/terasoluna/tourreservation/app/managereservation/ManageReservationControllerTest.java
- terasoluna-tourreservation-web/src/test/java/org/terasoluna/tourreservation/app/reservetour/ReserveTourControllerTest.java
> correspond to the 'Spring Secuity 4.0.' #339

- terasoluna-tourreservation-web/pom.xml
> change dependency web to web-jsp. issues:#344

- .travis.yml
- pom.xml
> Update Java version to 1.8 issues:#238

- terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-security.xml
> modify 'auto-config' configuration #341

- terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-security.xml
- terasoluna-tourreservation-web/src/main/webapp/WEB-INF/views/reservetour/reserveForm.jsp
> #343 Remove RedirectAuthenticationHandler

- terasoluna-tourreservation-domain/src/test/java/org/terasoluna/tourreservation/domain/repository/reserve/ReserveRepositoryImplTest.java
(cherry picked from commit 155c7f62eb57ffa06cb90363674b2b97531ec711)
terasolunaorg/terasoluna-tourreservation#345.
> [5.0.x] Fix error of ReserveRepositoryImplTest#testFindByCustomer01 terasolunaorg/terasoluna-tourreservation#345

- terasoluna-tourreservation-domain/src/test/java/org/terasoluna/tourreservation/domain/repository/reserve/ReserveRepositoryImplTest.java
(cherry picked from commit 155c7f62eb57ffa06cb90363674b2b97531ec711)
Please review terasolunaorg/terasoluna-tourreservation#345.
> [1.0.x] Fix error of ReserveRepositoryImplTest#testFindByCustomer01 terasolunaorg/terasoluna-tourreservation#345

- terasoluna-tourreservation-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml
- terasoluna-tourreservation-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml.env.ftl
Please review terasolunaorg/terasoluna-tourreservation#338.
> Fix connection pool settings(maxWaitMillis, maxTotal) for tomcat8 terasolunaorg/terasoluna-tourreservation#338

- terasoluna-tourreservation-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml
- terasoluna-tourreservation-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml.env.ftl
(cherry picked from commit 275b65031c15fa7a612d493c584c896e2fcbe9a8)
Please review terasolunaorg/terasoluna-tourreservation#338.
> [5.0.x] Fix connection pool settings(maxWaitMillis, maxTotal) for tomcat8 terasolunaorg/terasoluna-tourreservation#338

- pom.xml
#354
jdbc postgresql version up 9.4-1206-jdbc41
> jdbc postgresql version up 9.4-1206-jdbc41 #354

- terasoluna-tourreservation-parent/pom.xml
#354 
jdbc postgresql version up 9.4-1206-jdbc41 5.0.x
> jdbc postgresql version up 9.4-1206-jdbc41 5.0.x

- terasoluna-tourreservation-parent/pom.xml
#356 
jdbc postgresql version up 9.4-1206-jdbc41 1.0.x
> jdbc postgresql version up 9.4-1206-jdbc41 1.0.x

- terasoluna-tourreservation-env/configs/tomcat-postgresql/resources/META-INF/spring/terasoluna-tourreservation-env.xml
- terasoluna-tourreservation-env/configs/tomcat8-postgresql/resources/META-INF/spring/terasoluna-tourreservation-env.xml
Please review terasolunaorg/terasoluna-tourreservation#361
> Fix terasoluna-tourreservation-env.xml #361

- README.md
> Add travis-ci badge for 5.1.x on README.md #364

- terasoluna-tourreservation-domain/pom.xml
- terasoluna-tourreservation-env/pom.xml
- terasoluna-tourreservation-initdb/pom.xml
- terasoluna-tourreservation-parent/pom.xml
- terasoluna-tourreservation-selenium/pom.xml
- terasoluna-tourreservation-web/pom.xml
> Update to 1.0.5-SNAPSHOT #367

- terasoluna-tourreservation-domain/pom.xml
- terasoluna-tourreservation-env/pom.xml
- terasoluna-tourreservation-initdb/pom.xml
- terasoluna-tourreservation-parent/pom.xml
- terasoluna-tourreservation-selenium/pom.xml
- terasoluna-tourreservation-web/pom.xml
> Update to 5.0.3-SNAPSHOT #368

- .travis.yml
> fix travis.yml #375

- pom.xml
- terasoluna-tourreservation-domain/pom.xml
- terasoluna-tourreservation-env/pom.xml
- terasoluna-tourreservation-initdb/pom.xml
- terasoluna-tourreservation-selenium/pom.xml
- terasoluna-tourreservation-web/pom.xml
> Update to 5.1.1-SNAPSHOT #369

- pom.xml
- terasoluna-tourreservation-domain/pom.xml
- terasoluna-tourreservation-env/pom.xml
- terasoluna-tourreservation-initdb/pom.xml
- terasoluna-tourreservation-selenium/pom.xml
- terasoluna-tourreservation-web/pom.xml
> Update to 5.2.0-SNAPSHOT #370

- terasoluna-tourreservation-web/pom.xml
> add a dependency to taglibs-standard-jstlel #379

- terasoluna-tourreservation-domain/pom.xml
- terasoluna-tourreservation-env/pom.xml
> Add the type in the description of the dependency #387

- terasoluna-tourreservation-web/src/main/resources/hibernate.properties
> Add property file hidernate.properties #380

- terasoluna-tourreservation-web/src/main/resources/hibernate.properties
Please review #380
(cherry picked from commit 721519caff725ae301bb2d254a4a24b62dcf7c5a)
> [5.1.x] Add property file hidernate.properties_JPA #380

- eclipse/formatter.xml
- pom.xml
- terasoluna-tourreservation-domain/pom.xml
- terasoluna-tourreservation-env/pom.xml
- terasoluna-tourreservation-selenium/pom.xml
- terasoluna-tourreservation-web/pom.xml
> apply new pom structure #391

- terasoluna-tourreservation-web/pom.xml
> add gfw-web-dependencies #391

- terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-mvc.xml
> add wordarround to CVE-2016-5007 #394

- terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-mvc.xml
Please review #394.
(cherry picked from commit 4505cc044e734d4c3b995f51b190e620aecea328)
> [5.1.x] add wordarround to CVE-2016-5007 #394

- terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-mvc.xml
Please review #394.
(cherry picked from commit 4505cc044e734d4c3b995f51b190e620aecea328)
Conflicts:
terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-mvc.xml
> [5.0.x] add wordarround to CVE-2016-5007 #394

- terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-mvc.xml
Please review #394.
(cherry picked from commit 4505cc044e734d4c3b995f51b190e620aecea328)
Conflicts:
terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-mvc.xml
> [1.0.x] add wordarround to CVE-2016-5007 #394

- terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/LogInLogOutTest.java
- terasoluna-tourreservation-web/src/main/webapp/WEB-INF/views/login/form.jsp
> Reflect Spring Security failure-url JPA Test #395

- terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/LogInLogOutTest.java
- terasoluna-tourreservation-web/src/main/webapp/WEB-INF/views/login/form.jsp
> Remove failure-url JPA Test For 5.1.1 #395

- terasoluna-tourreservation-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml
- terasoluna-tourreservation-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml.env.ftl
- terasoluna-tourreservation-env/configs/tomcat8-postgresql/resources/META-INF/spring/tourreservation-codelist.properties
- terasoluna-tourreservation-env/configs/tomcat8-postgresql/resources/META-INF/spring/tourreservation-env.xml
- terasoluna-tourreservation-env/configs/tomcat8-postgresql/resources/META-INF/spring/tourreservation-infra.properties
- terasoluna-tourreservation-env/configs/tomcat8-postgresql/resources/logback.xml
- terasoluna-tourreservation-env/pom.xml
Please review #403.
Configurations (exclude `context.xml`) copied from `tomcat-postgresql` directory.
> add configurations for Tomcat8 #403

- pom.xml
- terasoluna-tourreservation-domain/pom.xml
- terasoluna-tourreservation-env/pom.xml
- terasoluna-tourreservation-initdb/pom.xml
- terasoluna-tourreservation-selenium/pom.xml
- terasoluna-tourreservation-web/pom.xml
> update to 5.3.0-SNAPSHOT #405

- .travis.yml
- pom.xml
- terasoluna-tourreservation-domain/pom.xml
- terasoluna-tourreservation-env/pom.xml
- terasoluna-tourreservation-initdb/pom.xml
- terasoluna-tourreservation-selenium/pom.xml
- terasoluna-tourreservation-web/pom.xml
> update to 5.2.1-SNAPSHOT #405 

- terasoluna-tourreservation-domain/pom.xml
- terasoluna-tourreservation-env/pom.xml
- terasoluna-tourreservation-initdb/pom.xml
- terasoluna-tourreservation-parent/pom.xml
- terasoluna-tourreservation-selenium/pom.xml
- terasoluna-tourreservation-web/pom.xml
> update to 1.0.6-SNAPSHOT #405

- pom.xml
- terasoluna-tourreservation-domain/pom.xml
- terasoluna-tourreservation-env/pom.xml
- terasoluna-tourreservation-initdb/pom.xml
- terasoluna-tourreservation-selenium/pom.xml
- terasoluna-tourreservation-web/pom.xml
> update to 5.1.2-SNAPSHOT #405

- README.md
Please review #406 
(cherry picked from commit 7184cc30d9587b3feff0f4abcadbe68b3409d5ba)
> [5.2.x] Add travis-ci badge for 5.2.x on README.md #406

- README.md
> Add travis-ci badge for 5.2.x on README.md #406

- ISSUE_TEMPLATE.md
- PULL_REQUEST_TEMPLATE.md
> Add issue and PR template. #413

- pom.xml
- terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/login/LoginController.java
- terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-mvc.xml
- terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-security.xml
- terasoluna-tourreservation-web/src/main/webapp/WEB-INF/web.xml
> Apply Spring IO Platform Athens-SR1 #416 #418

- terasoluna-tourreservation-domain/src/test/java/org/terasoluna/tourreservation/domain/repository/reserve/ReserveRepositoryImplTest.java
- terasoluna-tourreservation-domain/src/test/java/org/terasoluna/tourreservation/domain/repository/tourinfo/TourInfoRepositoryImplTest.java
Please review  terasolunaorg/terasoluna-tourreservation#419.
> deleted deprecated API used in Test Case class. terasolunaorg/terasoluna-tourreservation#419

- pom.xml
> update Postgresql JDBC Driver version. #421

- pom.xml
Please review terasolunaorg/terasoluna-tourreservation#421.
> Issues/421 update postgresql jdbc driver version 5.2.x

- pom.xml
Please review terasolunaorg/terasoluna-tourreservation#421.
> Issues/421 update postgresql jdbc driver version 5.1.x

- terasoluna-tourreservation-parent/pom.xml
Please review terasolunaorg/terasoluna-tourreservation#421.
> update Postgresql JDBC Driver version. terasolunaorg/terasoluna-tourreservation#421

- terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/error/ErrorController.java
- terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-security.xml
- terasoluna-tourreservation-web/src/main/webapp/WEB-INF/web.xml
> added error controller. #418

- .travis.yml
- terasoluna-tourreservation-parent/pom.xml
> change java-version -> 1.8 at [5.0.x] #432

- .travis.yml
- terasoluna-tourreservation-parent/pom.xml
> change java-version -> 1.8 at [1.0.x] #432

- terasoluna-tourreservation-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml
- terasoluna-tourreservation-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml.env.ftl
- terasoluna-tourreservation-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml
- terasoluna-tourreservation-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml.env.ftl
> Set defaultAutoCommit to false in context.xml terasolunaorg/terasoluna-tourreservation#438

- terasoluna-tourreservation-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml
- terasoluna-tourreservation-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml.env.ftl
- terasoluna-tourreservation-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml
- terasoluna-tourreservation-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml.env.ftl
(cherry picked from commit 71e43043fae95c20068a980df940ff9e5f280f02)
> [5.2.x] Set defaultAutoCommit to false in context.xml terasolunaorg/terasoluna-tourreservation#438

- terasoluna-tourreservation-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml
- terasoluna-tourreservation-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml.env.ftl
- terasoluna-tourreservation-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml
- terasoluna-tourreservation-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml.env.ftl
(cherry picked from commit 71e43043fae95c20068a980df940ff9e5f280f02)
> [5.1.x] Set defaultAutoCommit to false in context.xml terasolunaorg/terasoluna-tourreservation#438

- terasoluna-tourreservation-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml
- terasoluna-tourreservation-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml.env.ftl
- terasoluna-tourreservation-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml
- terasoluna-tourreservation-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml.env.ftl
(cherry picked from commit 71e43043fae95c20068a980df940ff9e5f280f02)
> [5.0.x] Set defaultAutoCommit to false in context.xml terasolunaorg/terasoluna-tourreservation#438

- terasoluna-tourreservation-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml
- terasoluna-tourreservation-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml.env.ftl
- terasoluna-tourreservation-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml
- terasoluna-tourreservation-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml.env.ftl
(cherry picked from commit 71e43043fae95c20068a980df940ff9e5f280f02)
> [1.0.x] Set defaultAutoCommit to false in context.xml terasolunaorg/terasoluna-tourreservation#438

- pom.xml
> Modified /pom.xml for Maven Central.#437

- terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-mvc.xml
> Add excludedExceptions #445

- terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-mvc.xml
> Modify typo (workarround -> workaround) #420

- terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-mvc.xml
> [5.2.x] Modify typo (workarround -> workaround) #420

- terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-mvc.xml
> [5.1.x] Modify typo (workarround -> workaround) #420

- terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-mvc.xml
> [5.0.x] Modify typo (workarround -> workaround) #420

- terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-mvc.xml
> [1.0.x] Modify typo (workarround -> workaround) #420

- terasoluna-tourreservation-domain/src/main/resources/META-INF/spring/terasoluna-tourreservation-infra.xml
> Modify typo (customerCode -> reserveNo) #454

- terasoluna-tourreservation-domain/src/main/resources/META-INF/spring/terasoluna-tourreservation-infra.xml
> [5.2.x] Modify typo (customerCode -> reserveNo) #454

- terasoluna-tourreservation-domain/src/main/resources/META-INF/spring/terasoluna-tourreservation-infra.xml
> [5.1.x] Modify typo (customerCode -> reserveNo) #454

- terasoluna-tourreservation-domain/src/main/resources/META-INF/spring/tourreservation-infra.xml
> [5.0.x] Modify typo (customerCode -> reserveNo) #454

- terasoluna-tourreservation-domain/src/main/resources/META-INF/spring/tourreservation-infra.xml
> [1.0.x] Modify typo (customerCode -> reserveNo) #454

- terasoluna-tourreservation-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml
- terasoluna-tourreservation-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml.env.ftl
- terasoluna-tourreservation-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml
- terasoluna-tourreservation-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml.env.ftl
Reverts terasolunaorg/terasoluna-tourreservation#439
> Revert "Set defaultAutoCommit to false in context.xml terasolunaorg/terasoluna-tourreservation#438"

- terasoluna-tourreservation-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml
- terasoluna-tourreservation-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml.env.ftl
- terasoluna-tourreservation-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml
- terasoluna-tourreservation-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml.env.ftl
Reverts terasolunaorg/terasoluna-tourreservation#440
> Revert "[5.2.x] Set defaultAutoCommit to false in context.xml terasolunaorg/terasoluna-tourreservation#438"

- terasoluna-tourreservation-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml
- terasoluna-tourreservation-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml.env.ftl
- terasoluna-tourreservation-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml
- terasoluna-tourreservation-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml.env.ftl
Reverts terasolunaorg/terasoluna-tourreservation#441
> Revert "[5.1.x] Set defaultAutoCommit to false in context.xml terasolunaorg/terasoluna-tourreservation#438"

- terasoluna-tourreservation-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml
- terasoluna-tourreservation-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml.env.ftl
- terasoluna-tourreservation-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml
- terasoluna-tourreservation-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml.env.ftl
Reverts terasolunaorg/terasoluna-tourreservation#442
> Revert "[5.0.x] Set defaultAutoCommit to false in context.xml terasolunaorg/terasoluna-tourreservation#438"

- terasoluna-tourreservation-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml
- terasoluna-tourreservation-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml.env.ftl
- terasoluna-tourreservation-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml
- terasoluna-tourreservation-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml.env.ftl
Reverts terasolunaorg/terasoluna-tourreservation#443
> Revert "[1.0.x] Set defaultAutoCommit to false in context.xml terasolunaorg/terasoluna-tourreservation#438"

- pom.xml
- terasoluna-tourreservation-domain/pom.xml
- terasoluna-tourreservation-env/pom.xml
- terasoluna-tourreservation-initdb/pom.xml
- terasoluna-tourreservation-selenium/pom.xml
- terasoluna-tourreservation-web/pom.xml
> [master]Update version to 5.4.0-SNAPSHOT.#474

- pom.xml
- terasoluna-tourreservation-domain/pom.xml
- terasoluna-tourreservation-env/pom.xml
- terasoluna-tourreservation-initdb/pom.xml
- terasoluna-tourreservation-selenium/pom.xml
- terasoluna-tourreservation-web/pom.xml
> [5.3.x]Update version to 5.3.1-SNAPSHOT.#474

- pom.xml
- terasoluna-tourreservation-domain/pom.xml
- terasoluna-tourreservation-env/pom.xml
- terasoluna-tourreservation-initdb/pom.xml
- terasoluna-tourreservation-selenium/pom.xml
- terasoluna-tourreservation-web/pom.xml
> [5.2.x]Update version to 5.2.2-SNAPSHOT.#474

- terasoluna-tourreservation-domain/pom.xml
- terasoluna-tourreservation-env/pom.xml
- terasoluna-tourreservation-initdb/pom.xml
- terasoluna-tourreservation-parent/pom.xml
- terasoluna-tourreservation-selenium/pom.xml
- terasoluna-tourreservation-web/pom.xml
> [1.0.x]Update version to 1.0.7-SNAPSHOT.#474

- .travis.yml
> Change to use terasoluna-gfw 5.3.x branch at .travis of 5.3.x branch #475

- README.md
> [master]Modify travis-ci badge on master in README.md.#481

- README.md
> [5.3.x]Add travis-ci badge for 5.3.x in README.md.#481 

- README.md
> [5.2.x]Remove travis-ci badge in README.md.#481

- README.md
> [5.1.x]Remove travis-ci badge in README.md.#481

- README.md
> [5.0.x]Remove travis-ci badge in README.md.#481

- README.md
> [1.0.x]Modified travis-ci badge in README.md.#481

- .travis.yml
> add firefox version at .travis.yml #496

- .travis.yml
- pom.xml
- terasoluna-tourreservation-domain/pom.xml
- terasoluna-tourreservation-env/pom.xml
- terasoluna-tourreservation-initdb/pom.xml
- terasoluna-tourreservation-selenium/pom.xml
- terasoluna-tourreservation-web/pom.xml
> [5.0.x] Apply multiple module project to 5.0.x #494

- ISSUE_TEMPLATE.md
> Add Final Solution section to Issue Template. #503

- terasoluna-tourreservation-env/configs/tomcat-postgresql/resources/logback.xml
- terasoluna-tourreservation-env/configs/tomcat8-postgresql/resources/logback.xml
- terasoluna-tourreservation-env/src/main/resources/logback.xml
- terasoluna-tourreservation-selenium/src/test/resources/logback.xml
> add doctype.#509

- terasoluna-tourreservation-env/configs/tomcat-postgresql/resources/logback.xml
- terasoluna-tourreservation-env/configs/tomcat8-postgresql/resources/logback.xml
- terasoluna-tourreservation-env/src/main/resources/logback.xml
- terasoluna-tourreservation-selenium/src/test/resources/logback.xml
> [5.3.x] add doctype. #509

- terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-mvc.xml
> Remove definition of trimTokens #510

- terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-mvc.xml
> [5.3.x] Remove definition of trimTokens #510

- pom.xml
- terasoluna-tourreservation-domain/pom.xml
- terasoluna-tourreservation-env/pom.xml
- terasoluna-tourreservation-initdb/pom.xml
- terasoluna-tourreservation-selenium/pom.xml
- terasoluna-tourreservation-web/pom.xml
> [5.3.x] fix SNAPSHOT version in pom.xml #524

- terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/common/FunctionTestSupport.java
> add firefox preference setting of no proxy. #522

- terasoluna-tourreservation-env/configs/tomcat85-postgresql/ContainerConfigXML/context.xml
- terasoluna-tourreservation-env/configs/tomcat85-postgresql/ContainerConfigXML/context.xml.env.ftl
- terasoluna-tourreservation-env/configs/tomcat85-postgresql/resources/META-INF/spring/terasoluna-tourreservation-codelist.properties
- terasoluna-tourreservation-env/configs/tomcat85-postgresql/resources/META-INF/spring/terasoluna-tourreservation-env.xml
- terasoluna-tourreservation-env/configs/tomcat85-postgresql/resources/META-INF/spring/terasoluna-tourreservation-infra.properties
- terasoluna-tourreservation-env/configs/tomcat85-postgresql/resources/dozer.properties
- terasoluna-tourreservation-env/configs/tomcat85-postgresql/resources/log4jdbc.properties
- terasoluna-tourreservation-env/configs/tomcat85-postgresql/resources/logback.xml
- terasoluna-tourreservation-env/pom.xml
> add profile of tomcat8.5. #523

- pom.xml
- terasoluna-tourreservation-domain/pom.xml
- terasoluna-tourreservation-env/pom.xml
- terasoluna-tourreservation-initdb/pom.xml
- terasoluna-tourreservation-selenium/pom.xml
- terasoluna-tourreservation-web/pom.xml
> update to 5.5.0-SNAPSHOT #534

- pom.xml
- terasoluna-tourreservation-domain/pom.xml
- terasoluna-tourreservation-env/pom.xml
- terasoluna-tourreservation-initdb/pom.xml
- terasoluna-tourreservation-selenium/pom.xml
- terasoluna-tourreservation-web/pom.xml
> [5.4.x] update to 5.4.1-SNAPSHOT #534

- README.md
> [5.4.x] change link to badge in README.md #533

- .travis.yml
> fixed travis.yml #541

- .travis.yml
(cherry picked from commit 885c91dbf094c8d4f7acd93039ffbb62c5a0299c)
Please review #541
> [5.4.x] fixed travis.yml #541

- .travis.yml
(cherry picked from commit 885c91dbf094c8d4f7acd93039ffbb62c5a0299c)
Please review #541 .
> [5.3.x] fixed travis.yml #541

- .travis.yml
> change GFW_BRANCH to 5.4.x #539

- pom.xml
- terasoluna-tourreservation-domain/pom.xml
- terasoluna-tourreservation-env/pom.xml
- terasoluna-tourreservation-initdb/pom.xml
- terasoluna-tourreservation-selenium/pom.xml
- terasoluna-tourreservation-web/pom.xml
> [5.4.x] update snapshot version to 5.4.2 #551

- pom.xml
- terasoluna-tourreservation-domain/pom.xml
- terasoluna-tourreservation-env/pom.xml
- terasoluna-tourreservation-initdb/pom.xml
- terasoluna-tourreservation-selenium/pom.xml
- terasoluna-tourreservation-web/pom.xml
> [5.3.x] update snapshot version to 5.3.3 #551

- .travis.yml
Please review #541 
(cherry picked from commit 885c91d)
> [5.2.x] fixed travis.yml #541

- .travis.yml
Please review #541 
(cherry picked from commit 885c91d)
> [5.1.x] fixed travis.yml #541

- .travis.yml
Please review #541 
(cherry picked from commit 885c91d)
> [5.0.x] fixed travis.yml #541

- .travis.yml
Please review #541 
(cherry picked from commit 885c91d)
> [1.0.x] fixed travis.yml #541

- pom.xml
> update postgresql driver #569

- terasoluna-tourreservation-env/configs/tomcat9-postgresql/ContainerConfigXML/context.xml
- terasoluna-tourreservation-env/configs/tomcat9-postgresql/ContainerConfigXML/context.xml.env.ftl
- terasoluna-tourreservation-env/configs/tomcat9-postgresql/resources/META-INF/spring/terasoluna-tourreservation-codelist.properties
- terasoluna-tourreservation-env/configs/tomcat9-postgresql/resources/META-INF/spring/terasoluna-tourreservation-env.xml
- terasoluna-tourreservation-env/configs/tomcat9-postgresql/resources/META-INF/spring/terasoluna-tourreservation-infra.properties
- terasoluna-tourreservation-env/configs/tomcat9-postgresql/resources/dozer.properties
- terasoluna-tourreservation-env/configs/tomcat9-postgresql/resources/log4jdbc.properties
- terasoluna-tourreservation-env/configs/tomcat9-postgresql/resources/logback.xml
- terasoluna-tourreservation-env/pom.xml
> add profile of tomcat9+postgresql #565

- .travis.yml
- pom.xml
- terasoluna-tourreservation-domain/pom.xml
- terasoluna-tourreservation-domain/src/main/java/org/terasoluna/tourreservation/domain/repository/tourinfo/TourInfoRepositoryImpl.java
- terasoluna-tourreservation-domain/src/main/java/org/terasoluna/tourreservation/domain/service/customer/CustomerServiceImpl.java
- terasoluna-tourreservation-domain/src/main/java/org/terasoluna/tourreservation/domain/service/reserve/AuthorizedReserveSharedServiceImpl.java
- terasoluna-tourreservation-domain/src/main/java/org/terasoluna/tourreservation/domain/service/reserve/ReserveServiceImpl.java
- terasoluna-tourreservation-domain/src/main/java/org/terasoluna/tourreservation/domain/service/tourinfo/PriceCalculateSharedServiceImpl.java
- terasoluna-tourreservation-domain/src/main/java/org/terasoluna/tourreservation/domain/service/tourinfo/TourInfoSharedServiceImpl.java
- terasoluna-tourreservation-domain/src/main/java/org/terasoluna/tourreservation/domain/service/userdetails/ReservationUserDetailsService.java
- terasoluna-tourreservation-domain/src/main/resources/META-INF/dozer/domain-mapping.xml
- terasoluna-tourreservation-domain/src/test/java/org/terasoluna/tourreservation/domain/repository/tourinfo/TourInfoRepositoryImplTest.java
- terasoluna-tourreservation-domain/src/test/java/org/terasoluna/tourreservation/domain/service/customer/CustomerServiceImplTest.java
- terasoluna-tourreservation-domain/src/test/java/org/terasoluna/tourreservation/domain/service/reserve/ReserveServiceImplSecurityTest.java
- terasoluna-tourreservation-domain/src/test/java/org/terasoluna/tourreservation/domain/service/reserve/ReserveServiceImplTest.java
- terasoluna-tourreservation-domain/src/test/java/org/terasoluna/tourreservation/domain/service/tourinfo/TourInfoServiceImplTest.java
- terasoluna-tourreservation-domain/src/test/java/org/terasoluna/tourreservation/domain/service/tourinfo/TourInfoSharedServiceImplTest.java
- terasoluna-tourreservation-domain/src/test/resources/test-context.xml
- terasoluna-tourreservation-env/pom.xml
- terasoluna-tourreservation-initdb/pom.xml
- terasoluna-tourreservation-selenium/pom.xml
- terasoluna-tourreservation-web/pom.xml
- terasoluna-tourreservation-web/src/main/resources/META-INF/spring/applicationContext.xml
- terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-mvc.xml
- terasoluna-tourreservation-web/src/test/java/org/terasoluna/tourreservation/app/managecustomer/ManageCustomerControllerTest.java
- terasoluna-tourreservation-web/src/test/java/org/terasoluna/tourreservation/app/managereservation/ManageReservationControllerTest.java
- terasoluna-tourreservation-web/src/test/java/org/terasoluna/tourreservation/app/reservetour/ReserveTourControllerTest.java
- terasoluna-tourreservation-web/src/test/java/org/terasoluna/tourreservation/app/reservetour/ReserveTourHelperTest.java
- terasoluna-tourreservation-web/src/test/java/org/terasoluna/tourreservation/app/searchtour/SearchTourControllerTest.java
Please review #567 #576 #577 #578 #579 #580 #581 #582 .
Original PR
#568 
Overview
- #567
update version 5.5.0-SNAPSHOT -> 5.5.0.RC2-SNAPSHOT
b90effc5e52e03e63368d8f8c4f789013ca1c990 
- #576
change target field to be designated from foreign key to non-foreign key, to fetch to avoid lazy init exception
219c86f344771f50a0fc80a14d79f037ea6d53e3 
- #577
modified to correspond to change of dozer specification
c94bcc607d0bd48e84d814cd840ebf79c00e9bd3
- #578
respond to changes in methods(spring-data-commons)
c9080fcd0cb3b4a8f28410d5e437d2424dd76a42 
- #579 
respond to change of improvement of Pageable
d059b4ab768203226e98831e9bafa53aeac9c631 
- #580 
respond to change of improvement of ArgumentMatchers
66d7af0429f070dc49ccfe807a7e0d98377dca40 
- #581
update `cargo-maven2-plugin` version …
> update to 5.5.0.RC2-SNAPSHOT #567 #576 #577 #578 #579 #580 #581 #582 #584

- terasoluna-tourreservation-web/src/main/resources/ValidationMessages_ja.properties
Please review #559.
replace max and min of properties message.
Once merged, reflect fix to `terasoluna-tourreservation-mybatis`.
> fix property message #559

- terasoluna-tourreservation-web/src/main/resources/ValidationMessages_ja.properties
Please review #560.  
delete message corresponding to A.
Once merged, reflect fix to terasoluna-tourreservation-mybatis.
> delete extra message #560

- pom.xml
- terasoluna-tourreservation-domain/src/main/java/org/terasoluna/tourreservation/domain/service/reserve/ReserveServiceImpl.java
- terasoluna-tourreservation-domain/src/main/resources/META-INF/dozer/domain-mapping.xml
- terasoluna-tourreservation-domain/src/test/java/org/terasoluna/tourreservation/domain/service/reserve/ReserveServiceImplTest.java
- terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/managecustomer/ManageCustomerController.java
- terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/managereservation/ManageReservationController.java
- terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/managereservation/ManageReservationHelper.java
- terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/reservetour/ReserveTourHelper.java
- terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/searchtour/SearchTourController.java
- terasoluna-tourreservation-web/src/test/java/org/terasoluna/tourreservation/app/managecustomer/ManageCustomerControllerTest.java
- terasoluna-tourreservation-web/src/test/java/org/terasoluna/tourreservation/app/managereservation/ManageReservationControllerTest.java
- terasoluna-tourreservation-web/src/test/java/org/terasoluna/tourreservation/app/reservetour/ReserveTourHelperTest.java
- terasoluna-tourreservation-web/src/test/java/org/terasoluna/tourreservation/app/searchtour/SearchTourControllerTest.java
> [Cairo-SR3]Change Lombok' version to 1.18.2 #585 [Dozer 6.4.1]Upgrade Dozer #586

- terasoluna-tourreservation-web/src/main/resources/ValidationMessages_ja.properties
Please review #559  .
It is backport.
(cherry-pick : beeb77c)
> [backport]fix property message #559

- terasoluna-tourreservation-web/src/main/resources/ValidationMessages_ja.properties
Please review #560 .
It is backport.
(cherry-pick : 4302e41)
> [backport]delete extra message #560

- pom.xml
> update ver postgresql #595

- pom.xml
> [Brussels-SR14]Change Lombok' version to 1.18.4 #585

- ISSUE_TEMPLATE.md
Please review #598.
- Delete `Final Solution` 
- Add version template into `Fix Version/s`
- Change markdown syntax for listing
> update issue template #598

- .travis.yml
- README.md
- pom.xml
- terasoluna-tourreservation-selenium/pom.xml
- terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/common/FunctionTestSupport.java
- terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/common/WebDriverListenerImpl.java
- terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/CustomerRegisterTest.java
- terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/CustomerRegisterValidateTest.java
- terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/LanguageSwitchTest.java
- terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/LogInLogOutTest.java
- terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/LogInReservUpdateTest.java
- terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/SystemErrorTest.java
- terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/TokenCheckErrorTest.java
- terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/TourSearchPaginationTest.java
- terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/TourSearchRegistValidateTest.java
- terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/TourSearchValidateTest.java
- terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/UnLogInTourSearchTest.java
- terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/UnauthorizedAccessTest.java
- terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/WaitWebDriverEventListener.java
- terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/WebDriverListenerImpl.java
- terasoluna-tourreservation-selenium/src/test/resources/META-INF/spring/selenium.properties
- terasoluna-tourreservation-selenium/src/test/resources/META-INF/spring/seleniumContext.xml
> Update from Selenium 2 to Selenium 3 #573

- .travis.yml
- ISSUE_TEMPLATE.md
- pom.xml
- terasoluna-tourreservation-domain/pom.xml
- terasoluna-tourreservation-env/pom.xml
- terasoluna-tourreservation-initdb/pom.xml
- terasoluna-tourreservation-selenium/pom.xml
- terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/common/constants/MessageKeys.java
- terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/CustomerRegisterValidateTest.java
- terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/TourSearchValidateTest.java
- terasoluna-tourreservation-selenium/src/test/resources/ValidationMessages_en.properties
- terasoluna-tourreservation-selenium/src/test/resources/ValidationMessages_ja.properties
- terasoluna-tourreservation-web/pom.xml
- terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/managecustomer/CustomerForm.java
- terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/searchtour/SearchTourForm.java
- terasoluna-tourreservation-web/src/main/resources/ValidationMessages_en.properties
- terasoluna-tourreservation-web/src/main/resources/ValidationMessages_ja.properties
Please review #601 #602 #603 #588.
> apply spring boot dependencies 2.1.2 #601 #602 #603 #588

- .travis.yml
> fix build profile of terasoluna-gfw #602

- terasoluna-tourreservation-domain/src/main/resources/META-INF/spring/terasoluna-tourreservation-codelist.xml
- terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-mvc.xml
> fix fallbackTo property to codelist difinition #609

- pom.xml
> update jdbc driver #612

- terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/managereservation/ReservationReportPdfStamperView.java
- terasoluna-tourreservation-web/src/test/java/org/terasoluna/tourreservation/app/managereservation/ReservationReportPdfStamperViewTest.java
Please review #582 .
A Unit Test to implementation for #582 is added .
> add Unit Test #582

- terasoluna-tourreservation-web/pom.xml
- terasoluna-tourreservation-web/src/test/java/org/terasoluna/tourreservation/app/reservetour/ReserveTourControllerTest.java
(cherry picked from commit 4e891c747a1bc25c8a5b907e8208ae2f83967cf2)
Please review #584 .
This PR is backport for 5.4.x .
> [5.4.x] use UserDetails at ReserveTourControllerTest #584

- ISSUE_TEMPLATE.md
- pom.xml
- terasoluna-tourreservation-domain/pom.xml
- terasoluna-tourreservation-env/pom.xml
- terasoluna-tourreservation-initdb/pom.xml
- terasoluna-tourreservation-selenium/pom.xml
- terasoluna-tourreservation-web/pom.xml
> update to 5.6.0-SNAPSHOT #618

- .travis.yml
- pom.xml
- terasoluna-tourreservation-domain/pom.xml
- terasoluna-tourreservation-env/pom.xml
- terasoluna-tourreservation-initdb/pom.xml
- terasoluna-tourreservation-selenium/pom.xml
- terasoluna-tourreservation-web/pom.xml
> update to 5.5.2-SNAPSHOT #618

- terasoluna-tourreservation-domain/src/main/resources/META-INF/spring/terasoluna-tourreservation-codelist.xml
- terasoluna-tourreservation-domain/src/main/resources/META-INF/spring/terasoluna-tourreservation-domain.xml
- terasoluna-tourreservation-domain/src/main/resources/META-INF/spring/terasoluna-tourreservation-infra.xml
- terasoluna-tourreservation-domain/src/test/resources/org/terasoluna/tourreservation/domain/service/reserve/ReserveServiceImplSecurityTest-context.xml
- terasoluna-tourreservation-domain/src/test/resources/test-context.xml
- terasoluna-tourreservation-env/configs/tomcat-postgresql/resources/META-INF/spring/terasoluna-tourreservation-env.xml
- terasoluna-tourreservation-env/configs/tomcat8-postgresql/resources/META-INF/spring/terasoluna-tourreservation-env.xml
- terasoluna-tourreservation-env/configs/tomcat85-postgresql/resources/META-INF/spring/terasoluna-tourreservation-env.xml
- terasoluna-tourreservation-env/src/main/resources/META-INF/spring/terasoluna-tourreservation-env.xml
- terasoluna-tourreservation-selenium/src/test/resources/META-INF/spring/seleniumContext.xml
- terasoluna-tourreservation-web/src/main/resources/META-INF/spring/applicationContext.xml
- terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-mvc.xml
- terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-security.xml
> [5.4.x] replace schema location for Spring from http to https #624

- terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/common/FirefoxDriverFactoryBean.java
- terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/common/FunctionTestSupport.java
- terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/CustomerRegisterTest.java
- terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/CustomerRegisterValidateTest.java
- terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/LanguageSwitchTest.java
- terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/LogInLogOutTest.java
- terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/LogInReservUpdateTest.java
- terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/SystemErrorTest.java
- terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/TokenCheckErrorTest.java
- terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/TourSearchPaginationTest.java
- terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/TourSearchRegistValidateTest.java
- terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/TourSearchValidateTest.java
- terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/UnLogInTourSearchTest.java
- terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/UnauthorizedAccessTest.java
- terasoluna-tourreservation-selenium/src/test/resources/META-INF/spring/seleniumContext.xml
Please review #573
Based on the following PR, I incorporated the correction not related to the Selenium update.
https://github.com/terasolunaorg/terasoluna-tourreservation/pull/607
> udpate selenium backport #573

- .travis.yml
Please review #638 #639 #641 #643 .
> Change Oracle JDK -> Open JDK #638 Adapt xvfb usage at Xenial environment #639 Suppress log output #641 Improvement Travis script #643

- .travis.yml
> Apply development/5.6.0 #640

- terasoluna-tourreservation-domain/src/main/resources/META-INF/spring/terasoluna-tourreservation-codelist.xml
- terasoluna-tourreservation-domain/src/main/resources/META-INF/spring/terasoluna-tourreservation-domain.xml
- terasoluna-tourreservation-domain/src/main/resources/META-INF/spring/terasoluna-tourreservation-infra.xml
- terasoluna-tourreservation-domain/src/test/resources/org/terasoluna/tourreservation/domain/service/reserve/ReserveServiceImplSecurityTest-context.xml
- terasoluna-tourreservation-domain/src/test/resources/test-context.xml
- terasoluna-tourreservation-env/configs/tomcat-postgresql/resources/META-INF/spring/terasoluna-tourreservation-env.xml
- terasoluna-tourreservation-env/configs/tomcat8-postgresql/resources/META-INF/spring/terasoluna-tourreservation-env.xml
- terasoluna-tourreservation-env/configs/tomcat85-postgresql/resources/META-INF/spring/terasoluna-tourreservation-env.xml
- terasoluna-tourreservation-env/configs/tomcat9-postgresql/resources/META-INF/spring/terasoluna-tourreservation-env.xml
- terasoluna-tourreservation-env/src/main/resources/META-INF/spring/terasoluna-tourreservation-env.xml
- terasoluna-tourreservation-selenium/src/test/resources/META-INF/spring/seleniumContext.xml
- terasoluna-tourreservation-web/src/main/resources/META-INF/spring/applicationContext.xml
- terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-mvc.xml
- terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-security.xml
Please review #624.
Cherry picked from commit bf22b3007bd5db0f1ce5ff48bbd9cd0e63ae784f .
> replace schema location for spring from http to https #624

- .travis.yml
Please review #638 #639 #641 #643 .
Cherry-pick from commit c252593 , decc71b, f4effec, 513e874 .
> [5.5.x] Change Oracle JDK -> Open JDK #638 Adapt xvfb usage at Xenial environment #639 Suppress log output #641 Improvement Travis script #643

- .travis.yml
Cherry-pick from commit 8742580, ad7ebf3 .
Modified Travis CI environment to Trusty.
> [5.4.x] Suppress log output #641 Improvement Travis script #643 Fix Travis CI environment for Trusty #638

- .travis.yml
Cherry-pick from commit c97508f, 5f14b86, 0cfccfb .
> [5.3.x] Suppress log output #641 Improvement Travis script #643 Fix Travis CI environment for Trusty #638

- .travis.yml
Cherry-pick from commit c025652, 01d84f3, fcc2406 .
> [5.2.x] Suppress log output #641 Improvement Travis script #643 Fix Travis CI environment for Trusty #638

- .travis.yml
Cherry-pick from commit 648f43b, fca0715, eccc173 .
> [5.1.x] Suppress log output #641 Improvement Travis script #643 Fix Travis CI environment for Trusty #638

- .travis.yml
Cherry-pick from commit 69f24e0, e62ea7d, acf0c3c .
> [5.0.x] Suppress log output #641 Improvement Travis script #643 Fix Travis CI environment for Trusty #638

- .travis.yml
Cherry-pick from commit 4029167, 4ac33f0, 7d1d6db .
> [1.0.x] Suppress log output #641 Improvement Travis script #643 Fix Travis CI environment for Trusty #638

- terasoluna-tourreservation-web/src/main/resources/ValidationMessages.properties
> remove validation messages #654

- terasoluna-tourreservation-env/configs/tomcat-postgresql/resources/META-INF/spring/terasoluna-tourreservation-env.xml
- terasoluna-tourreservation-env/configs/tomcat-postgresql/resources/log4jdbc.properties
- terasoluna-tourreservation-env/configs/tomcat-postgresql/resources/logback.xml
- terasoluna-tourreservation-env/configs/tomcat8-postgresql/resources/META-INF/spring/terasoluna-tourreservation-env.xml
- terasoluna-tourreservation-env/configs/tomcat8-postgresql/resources/log4jdbc.properties
- terasoluna-tourreservation-env/configs/tomcat85-postgresql/resources/META-INF/spring/terasoluna-tourreservation-env.xml
- terasoluna-tourreservation-env/configs/tomcat85-postgresql/resources/log4jdbc.properties
- terasoluna-tourreservation-env/configs/tomcat9-postgresql/resources/META-INF/spring/terasoluna-tourreservation-env.xml
- terasoluna-tourreservation-env/configs/tomcat9-postgresql/resources/log4jdbc.properties
- terasoluna-tourreservation-env/src/main/resources/META-INF/spring/terasoluna-tourreservation-env.xml
- terasoluna-tourreservation-env/src/main/resources/log4jdbc.properties
- terasoluna-tourreservation-env/src/main/resources/logback.xml
> remove log4jdbc-remix #657

- terasoluna-tourreservation-web/src/main/resources/META-INF/spring/applicationContext.xml
> add Argon2PasswordEncoder, SCryptPasswordEncoder #660

- pom.xml
> update JDBC driver #656

- terasoluna-tourreservation-web/pom.xml
> upgrade hamcrest to 2.x #664

- pom.xml
> upgrade jdbc 42.2.9 #656

- terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/error/ErrorController.java
- terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/login/LoginController.java
- terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/managereservation/ReservationReportPdfStamperView.java
Please review #674.
● `ErrorController.java `
　with an RequestMethod type(get or post) that calls each method.
● `LoginController.java `
　Because post requests are generated by [forwarding](https://github.com/terasolunaorg/terasoluna-tourreservation/blob/master/terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-security.xml#L40), both Get and POST are accepted.
　This fix does not resolve SonarQube's point.
● `ReservationReportPdfStamperView.java`
　The policy of the modification is as follows.
　https://rules.sonarsource.com/java/tag/multi-threading/RSPEC-2885  
　The name of the variable is the same as [ManageReservationHelper](https://github.com/terasolunaorg/terasoluna-tourreservation/blob/1862c937050faaa07837a68d4e3a2878099b2b17/terasoluna-tourreservation-web/src/mai …
> remove static modifier #674

- pom.xml
- terasoluna-tourreservation-domain/pom.xml
- terasoluna-tourreservation-env/pom.xml
- terasoluna-tourreservation-initdb/pom.xml
- terasoluna-tourreservation-selenium/pom.xml
- terasoluna-tourreservation-web/pom.xml
> update 5.7.0-SNAPSHOT #679

- README.md
- pom.xml
- terasoluna-tourreservation-domain/pom.xml
- terasoluna-tourreservation-env/pom.xml
- terasoluna-tourreservation-initdb/pom.xml
- terasoluna-tourreservation-selenium/pom.xml
- terasoluna-tourreservation-web/pom.xml
> update 5.6.1-SNAPSHOT #679

- .travis.yml
> update postgre, firefox. #678

- .travis.yml
Please review https://github.com/terasolunaorg/terasoluna-tourreservation/issues/678#issuecomment-747116810 .
> setting param PGPORT. #678

- .travis.yml
(cherry picked from commit 433fa2e2af1b9482af7f8e063302575e23101aaf)
Please review #689
- When I checked the settings of travis.ci below, I confirmed that the correction was reflected.
https://travis-ci.org/github/terasolunaorg/terasoluna-tourreservation/builds/746907622/config
> [5.6.x]update postgresql, firefox in travis.yml #689

- pom.xml
- terasoluna-tourreservation-domain/pom.xml
- terasoluna-tourreservation-env/pom.xml
- terasoluna-tourreservation-initdb/pom.xml
- terasoluna-tourreservation-selenium/pom.xml
- terasoluna-tourreservation-web/pom.xml
> update 5.6.2-SNAPSHOT #694

- pom.xml
- terasoluna-tourreservation-domain/pom.xml
- terasoluna-tourreservation-env/pom.xml
- terasoluna-tourreservation-initdb/pom.xml
- terasoluna-tourreservation-selenium/pom.xml
- terasoluna-tourreservation-web/pom.xml
> update 5.5.3-SNAPSHOT #696

- pom.xml
- terasoluna-tourreservation-domain/pom.xml
- terasoluna-tourreservation-web/pom.xml
- terasoluna-tourreservation-web/src/main/webapp/WEB-INF/web.xml
Please review https://github.com/terasolunaorg/terasoluna-tourreservation/issues/692
> depend jakarta lib. #692

- pom.xml
> set source to maven-javadoc-plugin #698

- pom.xml
(cherry picked from commit b7a8634a6465869d5020db8377b3d1deca1d7d97)
Please review #701
> [5.6.x] set source to maven-javadoc-plugin #698

- .gitignore
Please review #706 .
Removed unnecessary settings from gitignore.
> Remove unnecessary settings from gitignore #706

- .gitignore
(cherry picked from commit 929a84afe203ab58d180b1176bdca431cb2334ac)
Please review https://github.com/terasolunaorg/terasoluna-tourreservation/issues/708
Removed unnecessary settings from gitignore.
> [5.6.x]Remove unnecessary settings from gitignore #706

- pom.xml
- terasoluna-tourreservation-domain/pom.xml
- terasoluna-tourreservation-env/pom.xml
- terasoluna-tourreservation-initdb/pom.xml
- terasoluna-tourreservation-selenium/pom.xml
- terasoluna-tourreservation-web/pom.xml
> update to 5.8.0-SNAPSHOT. #710

- .travis.yml
- README.md
- pom.xml
- terasoluna-tourreservation-domain/pom.xml
- terasoluna-tourreservation-env/pom.xml
- terasoluna-tourreservation-initdb/pom.xml
- terasoluna-tourreservation-selenium/pom.xml
- terasoluna-tourreservation-web/pom.xml
Please review #712 
In .travis.yml, the cloned terasoluna-gfw was master, so it was fixed.
> update to 5.6.3-SNAPSHOT. #712

- pom.xml
- terasoluna-tourreservation-domain/pom.xml
- terasoluna-tourreservation-selenium/pom.xml
- terasoluna-tourreservation-web/pom.xml
Please review #686
See https://github.com/terasolunaorg/terasoluna-tourreservation/issues/686#issuecomment-891654903
Modified each pom.xml to match multi-blank.
> aligned plugin settings to blank project #686

- .travis.yml
Please review #719 
Added a command to check license headers in .travis.yml, similar to the comments below.
https://github.com/terasolunaorg/terasoluna-gfw/pull/1090#issuecomment-897361409
> check license header in travis #719

- eclipse/formatter.xml
- terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/common/constants/MessageKeys.java
- terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/LanguageSwitchTest.java
- terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/common/constants/MessageId.java
- terasoluna-tourreservation-web/src/test/java/org/terasoluna/tourreservation/app/searchtour/SearchTourControllerTest.java
Please review #721
I ran `mvn fomratter:format` to format it.
formatter.xml uses the one generated in https://github.com/terasolunaorg/terasoluna-gfw/pull/1092.
> modify formatter.xml and format source code #721

- pom.xml
Please review #719
See: https://github.com/terasolunaorg/terasoluna-tourreservation/issues/719#issuecomment-906922952
I executed `mvn license:check` and confirmed the operation.
> fix license-maven-plugin setteing #719

- .travis.yml
- pom.xml
> [5.7.x] fix license-maven-plugin setteing #719

- terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/error/ErrorController.java
- terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/managecustomer/ManageCustomerController.java
- terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/managereservation/ManageReservationController.java
- terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/menu/MenuController.java
- terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/reservetour/ReserveTourController.java
- terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/searchtour/SearchTourController.java
Please review #728 
For the following, we need to allow both GET and POST, so consider how to deal with another Issue.
https://github.com/terasolunaorg/terasoluna-tourreservation/blob/57b0eb80b2af5cb0a701e4724ed9d8971c49aa90/terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/login/LoginController.java#L30-L33
Confirmation method:
- Confirmed that all tests were successful locally and in GitLab.
> replaced RequestMapping with GetMapping or PostMapping #278

- pom.xml
> Match postgresql and ojdbc versions with Spring Boot #730

- pom.xml
(cherry picked from commit b2601abc28f2883e4dd32315d2ccc5d6443e8fbb)
Please review #732.
> Match postgresql and ojdbc versions with Spring Boot #730 #732

- README.md
- terasoluna-tourreservation-selenium/src/test/resources/wdm.properties
> geckodriver version upgrade #736

- README.md
- terasoluna-tourreservation-selenium/src/test/resources/wdm.properties
(cherry picked from commit b39dd6e00864aaa248241d70d4a96f5a19858a41)
Please review #738
> geckodriver version upgrade #736 #738

- terasoluna-tourreservation-env/configs/tomcat9-postgresql/resources/logback.xml
- terasoluna-tourreservation-env/src/main/resources/logback.xml
- terasoluna-tourreservation-selenium/src/test/resources/logback.xml
> changed log format #742

- terasoluna-tourreservation-env/configs/tomcat9-postgresql/resources/logback.xml
- terasoluna-tourreservation-env/src/main/resources/logback.xml
- terasoluna-tourreservation-selenium/src/test/resources/logback.xml
(cherry picked from commit b4b0b816725e430fa49de3616da6575a3f939330)
Please review #744
> [5.7.x] changed log format #742

- README.md
> remove build status. #748

- README.md
> remove build status. #750

- pom.xml
- terasoluna-tourreservation-domain/pom.xml
- terasoluna-tourreservation-env/pom.xml
- terasoluna-tourreservation-initdb/pom.xml
- terasoluna-tourreservation-selenium/pom.xml
- terasoluna-tourreservation-web/pom.xml
> update SNAPSHOT to 5.7.2 #756

- .github/ISSUE_TEMPLATE/3-backport-issue.md
> improved backport-issue template #758

- terasoluna-tourreservation-web/src/main/webapp/WEB-INF/views/managereservation/updateConfirm.jsp
Please review issues terasolunaorg/terasoluna-tourreservation#761
Backport operation log:
git cherry-pick -x 11a0fa41189cd41aaa5c9e75e9566e0dad986a71
> issue 555  reverse companyName and paymentCompanyname

- terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/managecustomer/CustomerForm.java
Please review #558 
There is no input check concerning the storable upper limit
Test result:
> issues558 add upper limit check to address item

- terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/CustomerRegisterValidateTest.java
Please review #558
- fix test source for upper limit check
> issue 558 fix test source for upper limit check
