.travis.yml
Please review terasolunaorg/terasoluna-tourreservation#273.
**Note:**
* For speedup, `git clone` for `terasoluna-gfw` perform with `--depth=1` option(latest history only). 
* For speedup, tests & generating javadoc jar & generating source jar for `terasoluna-gfw` skip on Travic-CI. 
* Default target branch of `terasoluna-gfw` is `master`. As option, target branch can override using `$GFW_BRANCH` (`$GFW_BRANCH` is adding by [settings page of Travis-CI](https://travis-ci.org/terasolunaorg/terasoluna-tourreservation/settings)).
=> Install latest snapshot of terasoluna-gfw before running build. terasolunaorg/terasoluna-tourreservation#273

terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/LogInLogOutTest.java, terasoluna-tourreservation-web/src/main/webapp/WEB-INF/views/login/form.jsp
Please review #395 .
The import org.openqa.selenium.By.id is never used.
delete
=> Remove failure-url JPA Test For Master #395

.travis.yml
This PR is backport for 5.3.x .
=> [5.3.x] add firefox version at .travis.yml #496

.travis.yml
(cherry picked from commit 0d66d22327242bfe2b28584e74d8f775bfa132aa)
This PR is backport for 5.2.x .
=> [5.2.x] add firefox version at .travis.yml #496

.travis.yml
(cherry picked from commit 0d66d22327242bfe2b28584e74d8f775bfa132aa)
This PR is backport for 5.1.x .
=> [5.1.x] add firefox version at .travis.yml #496

.travis.yml
(cherry picked from commit 0d66d22327242bfe2b28584e74d8f775bfa132aa)
This PR is backport for 5.0.x .
=> [5.0.x] add firefox version at .travis.yml #496

.travis.yml
(cherry picked from commit 0d66d22327242bfe2b28584e74d8f775bfa132aa)
This PR is backport for 1.0.x .
=> [1.0.x] add firefox version at .travis.yml #496

.travis.yml, pom.xml, terasoluna-tourreservation-domain/pom.xml, terasoluna-tourreservation-env/pom.xml, terasoluna-tourreservation-initdb/pom.xml, terasoluna-tourreservation-selenium/pom.xml, terasoluna-tourreservation-web/pom.xml
Please review #494 .
This PR is backport for 1.0.x .
When version of maven-dependency-plugin is 2.5, `dependency:copy` goal fails, so it was raised to 2.9 at fbb0e124336a668ee59fd7172933bfb7653665f3 commit .
=> [1.0.x] Apply multiple module project to 5.0.x #494

terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/common/FunctionTestSupport.java
=> [5.3.x] add firefox preference setting of no proxy. #522

terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/common/FunctionTestSupport.java
=> [5.2.x] add firefox preference setting of no proxy. #522

terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/common/FunctionTestSupport.java
=> [5.1.x] add firefox preference setting of no proxy. #522

terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/common/FunctionTestSupport.java
=> [5.0.x] add firefox preference setting of no proxy. #522

terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/common/FunctionTestSupport.java
=> [1.0.x] add firefox preference setting of no proxy. #522

terasoluna-tourreservation-env/configs/tomcat-postgresql/resources/logback.xml, terasoluna-tourreservation-env/configs/tomcat8-postgresql/resources/logback.xml, terasoluna-tourreservation-env/configs/tomcat85-postgresql/resources/logback.xml, terasoluna-tourreservation-env/configs/tomcat9-postgresql/resources/logback.xml, terasoluna-tourreservation-env/src/main/resources/logback.xml, terasoluna-tourreservation-selenium/src/test/resources/logback.xml
Please review #657.
It has been modified to match the following file.
https://github.com/terasolunaorg/terasoluna-gfw-web-multi-blank/blob/master/projectName-env/src/main/resources/logback.xml
`logback.xml` for `selenium` is exceptionally set to log output setting of `jdbc` only.
=> fix logback settings #657

pom.xml, terasoluna-tourreservation-domain/pom.xml
=> remove un-need dependency JAXB which changed to automatically be depended with dozer-core 6.5.0 #673

terasoluna-tourreservation-web/src/main/webapp/WEB-INF/web.xml
Please review #700.
Confirmation
Confirmed that the addition of the setting causes the output of the log on destroy, which was not output before the modification.
=>  Added a setting to output logs during destroy #700

terasoluna-tourreservation-web/src/main/webapp/WEB-INF/web.xml
(cherry picked from commit 442c97bdf6c8c60379f2855027e2cb6b5dc9bdbb)
Please review #704 .
Confirmation
Confirmed that the addition of the setting causes the output of the log on destroy, which was not output before the modification.
=> [5.6.x]Added a setting to output logs during destroy #700

pom.xml, terasoluna-tourreservation-env/pom.xml
Please review #686 
Confirmation is done with maven 3.8.1.
The changes other than the version upgrade are as follows:
- The `com.google.code:maven-license-plugin` has been changed to `com.mycila:license-maven-plugin` as in https://github.com/terasolunaorg/terasoluna-gfw/issues/600.
- The `build-helper-maven-plugin` didn't seem to be used so I removed it.
- Fixed the variable name of the plugin version to be `groupId.artifactId.pugin.version`.
https://github.com/terasolunaorg/terasoluna-tourreservation/commit/af1b74e120714b8cea6570a8123eda4e38c13f8f
=> update the plugin version #686

pom.xml, terasoluna-tourreservation-domain/pom.xml, terasoluna-tourreservation-env/pom.xml, terasoluna-tourreservation-selenium/pom.xml, terasoluna-tourreservation-web/pom.xml
Please review #715
The changes other than the version upgrade are as follows:
- The `com.google.code:maven-license-plugin` has been changed to `com.mycila:license-maven-plugin` as in https://github.com/terasolunaorg/terasoluna-gfw/issues/600.
- The `build-helper-maven-plugin` didn't seem to be used so I removed it.
- Fixed the variable name of the plugin version to be `groupId.artifactId.pugin.version`.
https://github.com/terasolunaorg/terasoluna-tourreservation/pull/716/commits/60dc18b78de6c833a2612e13a97deb842db8d395
=> [5.7.x] update the plugin version #686

terasoluna-tourreservation-web/src/main/webapp/WEB-INF/views/managereservation/updateConfirm.jsp
Please review #555.
> Issue: The display positions of 'companyName' and 'paymentCompanyname' are opposite. #555
> 
> Test result:
>     before:
>    after:
=> issue 555  reverse companyName and paymentCompanyname

terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/managecustomer/CustomerForm.java
Please review terasolunaorg/terasoluna-tourreservation#764
backport:There is no input check concerning the storable upper limit
Backport operation log:
`git cherry-pick -x 3abff48bfac3dfe554096370c0cce352f374909f`
=> Backport: There is no input check concerning the storable upper limit. #764
